include("sticky/types.jl")
include("sticky/boundary_velocity.jl")
include("sticky/loop_state.jl")
include("sticky/aggregate_clock_generic.jl")
include("sticky/residual_clocks.jl")
include("sticky/linear_clocks.jl")
include("sticky/scheduler.jl")
