# This file is generated by dev/scripts/update_precompile.sh.
# It intentionally contains only precompile(...) statements; do not add sampler
# execution here. Regenerate after changing sampler/grid dispatch internals.
